### ISSUE TITLE
Import of new data source fails silently if no name is given to the data set

### ISSUE THREAD

**Issue by gpaumier** [uwdata/lyra#221]
Hello,

When adding a new data source, it seems that giving a name to the data set is mandatory, but there is no indication that it is.

**Steps to reproduce:**
- Add a "New data source"
- Leave "Name" empty
- Add raw values
- Load

**Expected result:**
- The data set is assigned a name automatically, or the user gets an error message inviting them to name the data set.
- The data is imported and the widget closes.

**Actual result:**
- The data import widget closes, no data is imported, no error message is displayed.

**Comment by milimetric** [comment]
Hi :)  I was just wondering what plans you all have for lyra?  Is it seeing active development?

**Comment by arvind** [comment]
Hi @milimetric, a very fair question! With Vega 2 now released and stable, my attention is shifting back to Lyra. I'm in the process of prototyping a possible redesign and overhaul of the codebase, and hope to have news to share on this front early in the new year. If you have thoughts/comments on where you'd like to see Lyra go (e.g., what works well currently, what doesn't, feature requests, etc.), we're all ears!

**Comment by milimetric** [comment]
Thanks for the super quick response, @arvind :)  I loved playing with Lyra this past year.  It was really impressive what stuff could get accomplished.  I don't know that I have a lot of advice, except maybe to release an early version with bare minimum features that you can build on top of.  So instead of trying to cover a lot of Vega capabilities, especially the more complicated new stuff, just nailing down the basic idea.  You've got data streaming in from different sources, and you've got ways to transform that data.  Figure out how that basic general thing would work, and then just implement one type of data source and one type of transformation in Lyra.  Put it out there, we'll bang on it together.  If I don't have time to contribute code (which is mostly the sad truth with all my favorite OSS projects) I'll definitely give you as much feedback as you can handle :)

**Comment by arvind** [comment]
Closing old issues as we gear up for Lyra 2 development. Issues related to data importing will now be tracked in #235.
