### ISSUE TITLE
Vega Spec from Lyra example doesn't work in Vega editor

### ISSUE THREAD

**Issue by Cyberider** [uwdata/lyra#222]
When save the Vega JSON Spec from this "character" (miserables) example:
http://idl.cs.washington.edu/projects/lyra/app/#?example=les-mis

The online Vega editor does not process the file into a visualization:
http://vega.github.io/vega-editor/

Same when using JsFiddle.

I'm new to Lyra but my guess is that even though the Lyra app says you are saving a "Vega Json Spec" it is actually not a valid spec. Still in development?

Rick

**Comment by arvind** [comment]
Unfortunately this is because Lyra is currently built for Vega 1.4 and the Vega Editor at that link is on the recently released Vega 2.0. The two are mostly compatible (see [this documentation page](https://github.com/vega/vega/wiki/Upgrading-to-2.0) for upgrading a v1.x spec to v2). 

Upgrading Lyra to use Vega 2.0 is certainly on the roadmap but, because of limited people power resources, I'm unable to provide a firm date when that will happen. In the meanwhile, older versions of Vega (along with an older Vega Editor) are [available here](http://trifacta.github.io/vega/), and Lyra-generated specs should be compatible with them.
