### ISSUE TITLE
typeof undefined vs. ===

### ISSUE THREAD

**Issue by arvind** [uwdata/lyra#336]
Low priority nitpick, but wanted to double check the reasoning behind this decision. As I understand it, using `typeof` is safer when a particular variable has not been _declared_. However, it appears that [=== is significantly faster](https://jsperf.com/type-of-undefined-vs-undefined). A [quick grep](https://github.com/vega/lyra/files/210649/grep.txt) through the codebase suggests that our current usage need not worry about the former (and presumably, the linter should account for any usage before a declaration?). So, perhaps it's worth switching back to the latter?

**Comment by kadamwhite** [comment]
This used to be a huge issue before strict mode and good build processes, because it used to be possible to actually reassign `undefined`. That shouldn't be possible/relevant in our app, so using `=== undefined` ought to be safe; I'd been moving away from it because old habits die hard. I'd be fine moving back to using `undefined`.
