### ISSUE TITLE
Mark going beyond max axis value

### ISSUE THREAD

**Issue by ktbacher** [uwdata/lyra#505]
**Expected Behavior**
A line graph should not go above the max axis value

**Steps to reproduce behavior**
- chose cars dataset
- chose line mark
- drag mean_acceleration to y dropzone
- drag year to x dropzone
results in a chart with the line graph going above the max axis value

**Comment by jonathanzong** [comment]
Order matters here. If you drag `mean_acceleration` to `y` dropzone first, the error occurs because in `pipelineActions.ts`, under the `aggregatePipeline` function, the `groupby` array is empty. However, if you drag `year` first and then `mean_acceleration` second, the `groupby` array is populated with `year`.

**Comment by jonathanzong** [comment]
Same bug as https://github.com/vega/lyra/issues/489 ?

**Comment by jonathanzong** [comment]
see analogous to parseScale? -- look to see if aggregate already exists somewhere and add to empty groupby.

if it's already filled, we should test what feels most natural

**Comment by jonathanzong** [comment]
closed by 15795b8f5bcd8e301ee8d14ff9b95acca67ef5aa. punting question of what to do when second aggregate is dropped to a future issue
